### ISSUE TITLE
Link back or breadcrumb for Anthology pages

### ISSUE THREAD

**Issue by cncoleman** [cesta-online/anthology#3]
Does it make sense to, on all article pages, change the  "CESTA Research Anthology" header link so that it links to the first page of "this" research anthology? If you think not, can it be added to the sidebar on the right? or else a sort of breadcrumb after "CESTA Research Anthology"?
<img width="678" alt="Screenshot 2024-06-11 at 17 11 21" src="https://github.com/cesta-online/anthology/assets/288005/1a6479ab-10b8-44a3-b87d-5798adc91f9e">

**Comment by ddeepak95** [comment]
Hi @cncoleman,
Unfortunately, nothing much can be done in the header bands since it's getting injected by the script and making it dynamic is complex with undesirable side-effects. I can hyperlink 'Spring 2024' to the previous listing page. Does it help?

**Comment by cncoleman** [comment]
I think that's a great solution. Most likely people will use the back button on the browser!
